### ISSUE TITLE
Application label

### ISSUE THREAD

**Issue by atrinchillo** [clouddrove/terraform-labels#6]
Is it there a reason why you remove application from labels?
It means that during an upgrade who used this label need to remove it also from code

**Comment by anmolnagpal** [comment]
Hello @atrinchillo 

There was no specific reason, to remove application labels. we were trying to make it more structured, but If you need it.

We have 2 options

1st either I can move this module compatible with all versions (there are not many changes)
2nd add application label back

**Comment by atrinchillo** [comment]
Hi
No worries, thank you. 
I managed my code to respect this decision. I reported it just because, in case like this if we do not have backward compatibility, we can have problems.

**Comment by anmolnagpal** [comment]
Thanks, for the feedback, I'll make sure that we have backward compatibility.
